'use strict';
const http=require('node:http'),fs=require('node:fs');
const seed=JSON.parse(fs.readFileSync(process.env.GFLO_SEED_FILE,'utf8'));
let stock=seed.stock,nextId=1,failSave=Boolean(seed.failSaveOnce);const reservations=[];
function state(){return {stock,reservations:reservations.map(r=>({...r}))};}
function fields(value){if(!value||typeof value.reference!=='string'||!value.reference.trim())return 'Reference is required';if(!Number.isInteger(value.quantity)||value.quantity<1)return 'Quantity must be a positive whole number';return null;}
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Stock reservations</title><style>body{font:20px sans-serif;max-width:800px;margin:30px}label,input,button{display:block;margin:10px 0}input,button{font:inherit}li{margin:18px 0}[role=alert]{color:#900}</style><h1>Stock reservations</h1><p>Remaining: <strong id="stock">Loading</strong></p><form novalidate><label for="reference">Customer reference</label><input id="reference" aria-describedby="reference-error"><span id="reference-error"></span><label for="quantity">Quantity</label><input id="quantity" type="number" step="1" aria-describedby="quantity-error"><span id="quantity-error"></span><button id="save" type="submit">Reserve</button></form><p id="status" role="status"></p><p id="error" role="alert" tabindex="-1"></p><ul id="reservations" aria-label="Active reservations"></ul><script>
const form=document.querySelector('form'),ref=document.querySelector('#reference'),qty=document.querySelector('#quantity'),save=document.querySelector('#save'),err=document.querySelector('#error'),status=document.querySelector('#status');let editing=null;
function error(message,field){err.textContent=message;document.querySelector('#reference-error').textContent=field==='reference'?message:'';document.querySelector('#quantity-error').textContent=field==='quantity'?message:'';err.focus();}
async function refresh(){const s=await fetch('/api/state').then(r=>r.json());document.querySelector('#stock').textContent=s.stock;const list=document.querySelector('#reservations');list.replaceChildren();for(const r of s.reservations){const li=document.createElement('li');li.dataset.id=r.id;const text=document.createElement('span');text.textContent=r.reference+' — '+r.quantity;li.append(text);const edit=document.createElement('button');edit.textContent='Edit '+r.reference;edit.onclick=()=>{editing=r.id;ref.value=r.reference;qty.value=r.quantity;save.textContent='Save changes';ref.focus();};const cancel=document.createElement('button');cancel.textContent='Cancel '+r.reference;cancel.onclick=async()=>{if(!confirm('Cancel this reservation?'))return;const result=await fetch('/api/reservations/'+r.id,{method:'DELETE'});if(!result.ok){error('Cancel failed');return;}editing=null;form.reset();save.textContent='Reserve';status.textContent='Reservation cancelled';await refresh();};li.append(edit,cancel);list.append(li);}}
form.onsubmit=async event=>{event.preventDefault();err.textContent='';document.querySelector('#reference-error').textContent='';document.querySelector('#quantity-error').textContent='';if(!ref.value.trim()){error('Reference is required','reference');return;}const quantity=Number(qty.value);if(!Number.isInteger(quantity)||quantity<1){error('Quantity must be a positive whole number','quantity');return;}save.disabled=true;try{const result=await fetch('/api/reservations'+(editing?'/'+editing:''),{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:ref.value,quantity})});if(!result.ok){const data=await result.json();error(data.error);if(result.status===409)await refresh();return;}editing=null;form.reset();save.textContent='Reserve';status.textContent='Reservation saved';await refresh();}catch(e){error('Save failed; retry when ready');}finally{save.disabled=false;}};refresh();
</script></html>`;
const server=http.createServer(async(req,res)=>{const send=(code,value)=>{res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(html);}if(req.method==='GET'&&req.url==='/health')return send(200,{ok:true});if(req.method==='GET'&&req.url==='/api/state')return send(200,state());
const match=/^\/api\/reservations(?:\/(\d+))?$/.exec(req.url);if(!match)return send(404,{error:'Not found'});let body='';try{for await(const chunk of req){body+=chunk;if(body.length>8192)return send(413,{error:'Too large'});}const value=body?JSON.parse(body):{};const index=match[1]?reservations.findIndex(r=>r.id===Number(match[1])):-1;
if(req.method==='DELETE'&&index>=0){stock+=reservations[index].quantity;reservations.splice(index,1);return send(200,state());}
if(req.method!=='POST'&&req.method!=='PATCH')return send(404,{error:'Not found'});if(req.method==='PATCH'&&index<0)return send(404,{error:'Not found'});const invalid=fields(value);if(invalid)return send(422,{error:invalid});const previous=index>=0?reservations[index].quantity:0;const delta=value.quantity-previous;if(delta>stock)return send(409,{error:'Not enough stock; remaining inventory refreshed'});if(failSave){failSave=false;return send(503,{error:'Save failed; retry when ready'});}stock-=delta;if(index>=0)reservations[index]={...reservations[index],reference:value.reference.trim(),quantity:value.quantity};else reservations.push({id:nextId++,reference:value.reference.trim(),quantity:value.quantity});return send(200,state());}catch(error){return send(400,{error:'Invalid JSON'});}});
server.listen(3210,'127.0.0.1');
